#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int breakfastTextView = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int dateTextView = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int dinnerTextView = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int editText_Password = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int loadingProgressBar = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int lunchTextView = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int mealTextView = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int menu_EditIMData = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int menu_EditScribeData = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int menu_View_IM = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int reminderListView = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int soberDriverButton = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textView_Password = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditDataIMActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditDataScribeActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PasswordDialogFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Toolbar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int HomeMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int BetaChiTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Mono_Android_Theme_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
