#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int ReminderContextMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TeamContextMenu = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000f
			public const int breakfastTextView = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int buttonAddReminder = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int buttonAddTeam = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int buttonDatePicker = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int buttonSave = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int buttonSaveTeamChanges = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int buttonSetMeals = 2131230728;
			
			// aapt resource value: 0x7f08001a
			public const int buttonWIP = 2131230746;
			
			// aapt resource value: 0x7f08000b
			public const int dateTextView = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int dinnerTextView = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int editTextAddTeam = 2131230721;
			
			// aapt resource value: 0x7f080015
			public const int editTextBreakfast = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int editTextDinner = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int editTextLunch = 2131230742;
			
			// aapt resource value: 0x7f080000
			public const int editTextReminder = 2131230720;
			
			// aapt resource value: 0x7f080014
			public const int editText_Password = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int fragmentContainer = 2131230744;
			
			// aapt resource value: 0x7f080002
			public const int listViewEditIMStandings = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int listViewIMReminders = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int listViewRemindersMain = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int listViewRemindersScribe = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int loadingProgressBar = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int lunchTextView = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int mealTextView = 2131230734;
			
			// aapt resource value: 0x7f08001e
			public const int menu_EditIMData = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int menu_EditScribeData = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int menu_RefreshReminders = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int menu_View_IM = 2131230748;
			
			// aapt resource value: 0x7f08000a
			public const int numberPickerTeamPoints = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int soberDriverButton = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int textView_Password = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddReminderDialogFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddTeamDialogFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditDataIMStandingsActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditDataScribeActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditTeamPointsDialogFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainActivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PasswordDialogFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SetMealsDialogFragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ViewIMActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ViewIMRemindersTabFragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ViewIMStandingsTabFragment = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int HomeMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_BetaChi = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_BetaChiActionBar = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
